title: Zhenggang Xue
# author:
# email:
description: > # this means to ignore newlines until "baseurl:"
  Slience Space Seeking Fun

# twitter_username:
# github_username:
comments: true
paginate: 3

sass:
    style: compressed

# Disqus comments
disqus:
    shortname: zgxue #my_disqus_shortname
